apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: buildbot-ui
    name: buildbot-ui
  name: buildbot-ui-lb
spec:
  type: LoadBalancer
  selector:
    k8s-app: buildbot-master
  ports:
  - name: buildbot-ui
    port: 80
    targetPort: 8010
    protocol: TCP