---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: buildbot-master
    name: buildbot-master
  name: buildbot-master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: buildbot-master
    spec:
      containers:
      - name: buildbot-master
        image: gcr.io/uplifted-plate-210520/bbmaster:latest
        imagePullPolicy: Always
        env:
        - name: BUILDBOT_MASTER_URL
          valueFrom:
            configMapKeyRef:
              name: buildbot-config
              key: master_url
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: buildbot
              key: pg_password
        livenessProbe:
          httpGet:
            path: /
            port: buildbot-ui
          initialDelaySeconds: 120
          periodSeconds: 10
        ports:
        - containerPort: 8010
          name: buildbot-ui
          protocol: TCP
      serviceAccountName: default
